# Generated by Django 3.1.1 on 2020-10-06 15:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20201006_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 10, 6, 15, 49, 43, 590058, tzinfo=utc)),
        ),
    ]
