# Generated by Django 3.1.1 on 2020-10-06 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20201006_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 6, 15, 51, 3, 649284, tzinfo=utc)),
        ),
    ]
