# Generated by Django 3.1.1 on 2020-10-19 19:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20201006_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 19, 19, 38, 33, 491847, tzinfo=utc)),
        ),
    ]
