# Generated by Django 3.1.1 on 2020-10-26 22:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20201026_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 26, 22, 46, 34, 189534, tzinfo=utc)),
        ),
    ]
