# Generated by Django 3.1.1 on 2020-11-03 00:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_auto_20201026_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 3, 0, 18, 39, 166865, tzinfo=utc)),
        ),
    ]
