# Generated by Django 3.1.1 on 2020-12-01 15:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_auto_20201201_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 15, 45, 21, 365010, tzinfo=utc)),
        ),
    ]
