# Generated by Django 3.1.1 on 2020-12-08 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_auto_20201201_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 8, 16, 7, 11, 539443, tzinfo=utc)),
        ),
    ]
