# Generated by Django 3.1.1 on 2020-12-12 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_auto_20201208_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 16, 30, 1, 938878, tzinfo=utc)),
        ),
    ]
