# Generated by Django 3.1.1 on 2020-12-12 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_auto_20201212_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 17, 2, 55, 439799, tzinfo=utc)),
        ),
    ]
