# Generated by Django 3.1.1 on 2020-12-12 18:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_auto_20201212_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 12, 18, 8, 44, 505575, tzinfo=utc)),
        ),
    ]
