# Generated by Django 3.1.1 on 2020-12-14 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_auto_20201214_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 14, 18, 11, 43, 943687, tzinfo=utc)),
        ),
    ]
